services:
  laravel:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: shortener
    ports:
      - 8002:80
    env_file:
      - ./.env
    volumes:
      - local_data:/app/storage/app/public
    networks:
      - shared-net
    restart: always

networks:
  shared-net:
    external: true

volumes:
  local_data: